# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Catalog Service - Restore dependencies
      run: dotnet restore ./CatalogService/CatalogService.sln
    - name: Catalog Service - Build
      run: dotnet build ./CatalogService/CatalogService.sln --no-restore
    - name: Catalog Service - Test
      run: dotnet test ./CatalogService/CatalogService.sln --no-build --verbosity normal
    - name: Carting Service - Restore dependencies
      run: dotnet restore ./CartingService/CartingService.sln
    - name: Carting Service - Build
      run: dotnet build ./CartingService/CartingService.sln --no-restore
    - name: Carting Service - Test
      run: dotnet test ./CartingService/CartingService.sln --no-build --verbosity normal
